### ISSUE TITLE
Shaclex does not work with Jena 4

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo#231]
> java.lang.NoSuchMethodError: 'org.apache.jena.iri.IRI org.apache.jena.riot.system.IRIResolver.chooseBaseURI()'
	at es.weso.utils.JenaUtils$.$anonfun$relativizeStr$1(JenaUtils.scala:470)
	at scala.Option.getOrElse(Option.scala:189)

**Comment by berezovskyi** [comment]
Newer versions works with Jena 4 and updated validation was released in 5.1.1.
