### ISSUE TITLE
TRS Client tries to fetch rdf:nil

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo#91]
> [DEBUG] org.eclipse.lyo.client.OslcClient - Following redirect to https://www.w3.org/1999/02/22-rdf-syntax-ns
> [ERROR] org.eclipse.lyo.trs.client.util.TrackedResourceClient - Bad request

Stacktrace:

```
	at org.eclipse.lyo.trs.client.util.ClientUtil.extractResourceFromResponse(ClientUtil.java:152)
	at org.eclipse.lyo.trs.client.util.TrackedResourceClient.fetchTRSRemoteResource(TrackedResourceClient.java:49)
	at org.eclipse.lyo.trs.client.util.TrackedResourceClient.fetchRemoteChangeLog(TrackedResourceClient.java:110)
	at org.eclipse.lyo.trs.client.handlers.ConcurrentTrsProviderHandler.fetchRemoteChangeLogs(ConcurrentTrsProviderHandler.java:101)
	at org.eclipse.lyo.trs.client.handlers.ConcurrentTrsProviderHandler.fetchUpdatedChangeLogs(ConcurrentTrsProviderHandler.java:214)
	at org.eclipse.lyo.trs.client.handlers.ConcurrentTrsProviderHandler.pollAndProcessChanges(ConcurrentTrsProviderHandler.java:130)
	at org.eclipse.lyo.trs.client.handlers.ConcurrentTrsProviderHandler.update(ConcurrentTrsProviderHandler.java:66)
```

**Comment by berezovskyi** [comment]
This can be traced down to `org.eclipse.lyo.trs.client.handlers.ConcurrentTrsProviderHandler#fetchRemoteChangeLogs` and a missing URI check between

```java
previousChangeLog = currentChangeLog.getPrevious();
currentChangeLog = trsClient.fetchRemoteChangeLog(previousChangeLog);
```
